name: GitHub Actions Demo
on: [push]
jobs:
  CI:
    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: bundle install
      - run: pod install --repo-update

      # - run: ./build-ci.sh /tmp/PinLayout

      - name: Build PinLayout-iOS
        run: set -o pipefail && xcodebuild build -project PinLayout.xcodeproj -scheme PinLayout-iOS -sdk iphonesimulator15.2 -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.2' | xcpretty 

      - name: Build PinLayout-tvOS
        run: set -o pipefail && xcodebuild build -project PinLayout.xcodeproj -scheme PinLayout-tvOS -sdk appletvsimulator15.2 -destination 'platform=tvOS Simulator,name=Apple TV 4K (2nd generation),OS=15.2' | xcpretty 

      - name: Build PinLayout-macOS
        run: set -o pipefail && xcodebuild build -project PinLayout.xcodeproj -scheme PinLayout-macOS -sdk macosx12.1 | xcpretty 

      - name: Build PinLayoutSample
        run: set -o pipefail && xcodebuild build -workspace PinLayout.xcworkspace -scheme PinLayoutSample -sdk iphonesimulator15.2 -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.2' | xcpretty 

      - name: iOS unit test
        run: set -o pipefail && xcodebuild build test -workspace PinLayout.xcworkspace -scheme PinLayout-iOS -sdk iphonesimulator15.2 -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.2' | xcpretty 

      - name: tvOS unit test
        run: set -o pipefail && xcodebuild build test -workspace PinLayout.xcworkspace -scheme PinLayout-tvOS -sdk appletvos15.2 -destination 'platform=tvOS Simulator,name=Apple TV 4K (2nd generation),OS=15.2 | xcpretty 



# echo "==============================="
# echo "macOS unit test"
# echo "==============================="
# xcodebuild test -workspace PinLayout.xcworkspace -scheme PinLayout-macOS \
#    -derivedDataPath $DERIVED_DATA -sdk macosx12.1 \
#    | xcpretty

      - run: echo "🍏 This job's status is ${{ job.status }}."

  # Build:
  #     name: Test iOS 
  #     runs-on: macOS-latest
  #     # strategy:
  #     #   matrix:
  #     #     destination: ["OS=13.1,name=iPhone 11 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
  #     steps:
  #       - uses: actions/checkout@v2
  #       - run: ./build-ci.sh /tmp/PinLayout
  #       # - name: iOS - ${{ matrix.destination }}
  #       #   run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Alamofire.xcodeproj" -scheme "Alamofire iOS" -destination "${{ matrix.destination }}" clean test | xcpretty
  #       - run: echo "🍏 This job's status is ${{ job.status }}."
